# Generated by Django 3.2.2 on 2021-05-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210511_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneruser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
