# Generated by Django 3.2.1 on 2021-06-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.FloatField()),
                ('number_to_hire', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(default='')),
                ('remote_option', models.IntegerField(choices=[(1, 'Not Remote'), (2, 'Partial Remote'), (3, 'Full Remote'), (5, 'Multiple Options'), (6, 'Unspecified')], default=1)),
                ('salary_per_hour_option', models.IntegerField(choices=[(1, '$10.00+ /hour'), (2, '$12.50+ /hour'), (3, '$15.00+ /hour'), (4, '$17.50+ /hour'), (5, '$20.00+ /hour'), (6, '$22.50+ /hour'), (7, '$25.00+ /hour'), (8, '$27.50+ /hour'), (9, '$30.00+ /hour'), (10, '$32.50+ /hour'), (11, '$35.00+ /hour'), (12, '$37.50+ /hour'), (13, '$40.00+ /hour'), (14, '$42.50+ /hour'), (15, '$45.00+ /hour'), (16, '$47.50+ /hour'), (17, '$50.00+ /hour'), (18, '$52.50+ /hour'), (19, '$55.00+ /hour'), (20, 'Unspecified')], default=1)),
                ('job_type_option', models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Contract'), (4, 'Temporary'), (5, 'Per Diem'), (6, 'Multiple Options'), (7, 'Unspecified')], default=1)),
                ('exp_level_option', models.IntegerField(choices=[(1, 'Entry Level'), (2, 'Mid Level'), (3, 'Expert Level')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyjobs', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobKeyAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobKeyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobdetails', to='jobs.job')),
                ('job_key_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobkeydetails', to='jobs.jobkeydetail')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(default='')),
                ('full_description', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobdescriptions', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobabouts', to='jobs.job')),
                ('job_key_about_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobkeyabouts', to='jobs.jobkeyabout')),
            ],
        ),
    ]
