# Generated by Django 3.2.1 on 2021-05-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
