# Generated by Django 3.2.2 on 2021-05-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_added_by_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerskills', to='profiles.partneruser')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('office_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, upload_to='partners')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_added_by_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerreferences', to='profiles.partneruser')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_name', models.CharField(blank=True, max_length=255, null=True)),
                ('license_code', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('address_acquired', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, upload_to='partners')),
                ('is_compact', models.BooleanField(blank=True, default=False, null=True)),
                ('is_added_by_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerlicenses', to='profiles.partneruser')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerEducationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.IntegerField(choices=[(1, 'Image')], default=1)),
                ('media_content', models.FileField(blank=True, upload_to='partners')),
                ('is_active', models.IntegerField(default=1)),
                ('is_added_by_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnereducationmedias', to='profiles.partneruser')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.IntegerField(choices=[(1, 'Highschool'), (2, 'Associate'), (3, 'Bachelor'), (4, 'Master'), (5, 'Doctorate'), (6, 'Unspecified')], default=1)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_graduated', models.DateTimeField()),
                ('school_address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_added_by_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnereducations', to='profiles.partneruser')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField(default='')),
                ('is_added_by_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnercoverletters', to='profiles.partneruser')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cert_code', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('address_acquired', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, upload_to='partners')),
                ('is_added_by_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnercertifications', to='profiles.partneruser')),
            ],
        ),
    ]
