# Generated by Django 3.2.1 on 2021-06-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerworkhistory',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerworkhistories', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnerskill',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerskills', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnerresponsibility',
            name='work_history_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerresponsibilities', to='partners.partnerworkhistory'),
        ),
        migrations.AddField(
            model_name='partnerreference',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerreferences', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnerprofessionalsummary',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerprofessionalsummaries', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnerothermedia',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerothermedias', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnerlicense',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerlicenses', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnerlcmedia',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerlcmedias', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnereducationmedia',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnereducationmedias', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnereducation',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnereducations', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnercoverletter',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnercoverletters', to='profiles.partneruser'),
        ),
        migrations.AddField(
            model_name='partnercertification',
            name='auth_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnercertifications', to='profiles.partneruser'),
        ),
    ]
