# Generated by Django 3.2.2 on 2021-05-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnereducation',
            name='file',
            field=models.FileField(blank=True, upload_to='partners'),
        ),
    ]
