# Generated by Django 3.2.2 on 2021-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnereducation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercertification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnereducation',
            name='date_graduated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerlicense',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerreference',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnerreference',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
