# Generated by Django 3.2.1 on 2021-05-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20210513_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercertification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='partners'),
        ),
        migrations.AlterField(
            model_name='partnereducation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='partners'),
        ),
        migrations.AlterField(
            model_name='partnerlicense',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='partners'),
        ),
        migrations.AlterField(
            model_name='partnerreference',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='partners'),
        ),
    ]
