# Generated by Django 3.2.1 on 2021-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20210517_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnercertification',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnereducation',
            name='date_graduated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerlicense',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerreference',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerreference',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
