# Generated by Django 3.2.1 on 2021-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_auto_20210518_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlicense',
            name='is_compact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
