# Generated by Django 3.2.1 on 2021-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20210521_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnereducationmedia',
            name='media_name',
            field=models.CharField(default='no name', max_length=255),
        ),
    ]
