# Generated by Django 3.2.1 on 2021-05-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_partnereducationmedia_media_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnereducationmedia',
            old_name='media_name',
            new_name='media_filename',
        ),
    ]
