# Generated by Django 3.2.1 on 2021-05-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_partneruser_progress_mark'),
        ('partners', '0009_rename_media_name_partnereducationmedia_media_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOtherMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_filename', models.CharField(default='no name', max_length=255)),
                ('media_type', models.IntegerField(choices=[(1, 'Image')], default=1)),
                ('media_format', models.IntegerField(choices=[(1, 'JPG'), (2, 'PNG'), (3, 'PDF')], default=1)),
                ('media_content', models.FileField(blank=True, upload_to='other_files')),
                ('is_active', models.IntegerField(default=1)),
                ('is_added_by_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerothermedias', to='profiles.partneruser')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerLCMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_filename', models.CharField(default='no name', max_length=255)),
                ('media_type', models.IntegerField(choices=[(1, 'Image')], default=1)),
                ('media_format', models.IntegerField(choices=[(1, 'JPG'), (2, 'PNG'), (3, 'PDF')], default=1)),
                ('media_content', models.FileField(blank=True, upload_to='lc_files')),
                ('is_active', models.IntegerField(default=1)),
                ('is_added_by_admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerlcmedias', to='profiles.partneruser')),
            ],
        ),
    ]
