# Generated by Django 3.2.1 on 2021-05-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0011_partnerprofessionalsummary_partnerresponsibility_partnerworkhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerworkhistory',
            name='responsibilities',
            field=models.TextField(default=''),
        ),
    ]
