# Generated by Django 3.2.1 on 2021-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_town', models.CharField(blank=True, max_length=255, null=True)),
                ('address_region', models.CharField(blank=True, max_length=255, null=True)),
                ('address_country', models.CharField(blank=True, max_length=255, null=True)),
                ('address_zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(default='')),
            ],
        ),
    ]
